#UAT Database configuration
POSTGRES_SQL_USERNAME: pservicecore
POSTGRES_SQL_PASSWORD: zxcvbasdfg@123
POSTGRES_SQL_HOST: 10.1.152.21
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: pservicedb

#Server port
SERVER_PORT: 9094
ACTIVE_PROFILE: prod
#Ebirr configuration
EBIRR:
  url: https://payments.ebirr.com/asm
  schemaVersion: 1.0
  channelName: WEB
  serviceName: API_PURCHASE
  merchantUid: M0004225
#  merchantUid: 8118039
  paymentMethod: MWALLET_ACCOUNT
  apiKey: API-61937745AHX
  apiUserId: 10009074
  currency: ETB
  description: ebirr-payment
#For OTP Configuration
SEND_OTP:
  serviceCode: 960000
  channel: USSD
  Service_name: PhoneEnquiryService
#Appconnect Endpoints
APPCONNECT_URL:
  phoneEnqByAccNo: http://10.1.230.6:7081/v1/cbo/
  otpUrl: http://10.1.230.6:7081/v1/otp/send

COOP_INTERNAL:
  coopFtUrl: http://10.1.230.6:7081/v1/cbo/
